pipeline:
  release:
    image: rust:1-buster
    when: 
      event: tag
    secrets: [ gitea_api_key , cargo_registry_token ]
    commands:
      - cargo build --release
      - curl --user guillem:$GITEA_API_KEY --upload-file target/release/dr https://git.guillemborrell.es/api/packages/guillem/generic/dr/$CI_COMMIT_TAG/dr-linux-amd64
      - cargo publish --token $CARGO_REGISTRY_TOKEN